# Module 03 Pandas, Databases and Plotting

HD Sheets,  3/06/2026

In this exercise,  we will

1.) Connect to an SQLite database from within Python

2.) Grab the contents of an entire table from the database and move it into a Pandas dataframe

3.) Then do some exploratory data analysis on the pandas dataframe

I have written out the section of code for this example that connects to the database and retrieves the data table

In the exercise, you will use ideas from Module 02 on working with Pandas dataframes to do a bit of data processing

In [2]:
# import pandas and sqlite3 libraries

import pandas as pd
import sqlite3 
import os

In [5]:
#we are going to connect to the chinook data base, be sure a copy of the chinook.db is in the current working directory

infile="chinook.db"

In [6]:
# we can use the os library to check to be sure the chinook.db file is in the current
# working directory

os.listdir()

['Homework_1_Notebook.ipynb',
 'conda_python_and_environments_v_2.docx',
 'Boston_Assessment_Roll_2024.csv',
 'chinook.db',
 'Pair_Programming_Polars.ipynb',
 'PairExercise_database_connection.py',
 'Module 05 Software and Coding.docx',
 'Module 05 Software and Coding.pdf',
 'Module 05 Software and Coding_v2.docx',
 'Pair_Exercise_Python_Intro.ipynb',
 '.ipynb_checkpoints',
 'Regex_beginnings.ipynb',
 'Python_Understanding_your_variables.ipynb',
 'Misc_Pandas_stuff.ipynb',
 'Bits_and_pieces_Pandas.ipynb',
 'Intro_2_Strings.ipynb',
 'Untitled.ipynb',
 'C_example',
 'File_Names.ipynb',
 'Presentation_Graphics.ipynb',
 'Pandas_Tables_Sorting_Slicing.ipynb',
 'Exploratory_Data_Analysis_in_Python.ipynb',
 'Untitled1.ipynb']

In [7]:
# create the connection to the database

con=sqlite3.connect(infile)

#we need a database cursor as well
# some database systems do not require a separate cursor, just the connector

cur=con.cursor()

In [10]:
# we want to see list of the available tables

#set up the query- this is an SQL language command- we will see more detail on these later

sql_tables_query="SELECT name FROM sqlite_master WHERE (type='table');"

cur.execute(sql_tables_query)
table_listing=cur.fetchall()

# this will return a list of all the tables in the database

# we can print out each table in the list using a list comprehension

[(table) for table in table_listing]

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',),
 ('ranks',)]

In [15]:
# There is a nice way to do this, lets load the entire table into a data frame so we can easily work it

Tables_df=pd.read_sql_query("SELECT * FROM sqlite_master",con)
Tables_df

,type,name,tbl_name,rootpage,sql
0,table,albums,albums,2,"CREATE TABLE ""albums""\r\n(\r\n [AlbumId] IN..."
1,table,sqlite_sequence,sqlite_sequence,3,"CREATE TABLE sqlite_sequence(name,seq)"
2,table,artists,artists,4,"CREATE TABLE ""artists""\r\n(\r\n [ArtistId] ..."
3,table,customers,customers,5,"CREATE TABLE ""customers""\r\n(\r\n [Customer..."
4,table,employees,employees,8,"CREATE TABLE ""employees""\r\n(\r\n [Employee..."
5,table,genres,genres,10,"CREATE TABLE ""genres""\r\n(\r\n [GenreId] IN..."
6,table,invoices,invoices,11,"CREATE TABLE ""invoices""\r\n(\r\n [InvoiceId..."
7,table,invoice_items,invoice_items,13,"CREATE TABLE ""invoice_items""\r\n(\r\n [Invo..."
8,table,media_types,media_types,15,"CREATE TABLE ""media_types""\r\n(\r\n [MediaT..."
9,table,playlists,playlists,16,"CREATE TABLE ""playlists""\r\n(\r\n [Playlist..."
10,table,playlist_track,playlist_track,17,"CREATE TABLE ""playlist_track""\r\n(\r\n [Pla..."
11,index,sqlite_autoindex_playlist_track_1,playlist_track,18,None
12,table,tracks,tracks,20,"CREATE TABLE ""tracks""\r\n(\r\n [TrackId] IN..."
13,index,IFK_AlbumArtistId,albums,22,"CREATE INDEX [IFK_AlbumArtistId] ON ""albums"" (..."
14,index,IFK_CustomerSupportRepId,customers,23,"CREATE INDEX [IFK_CustomerSupportRepId] ON ""cu..."
15,index,IFK_EmployeeReportsTo,employees,24,"CREATE INDEX [IFK_EmployeeReportsTo] ON ""emplo..."
16,index,IFK_InvoiceCustomerId,invoices,26,"CREATE INDEX [IFK_InvoiceCustomerId] ON ""invoi..."
17,index,IFK_InvoiceLineInvoiceId,invoice_items,27,"CREATE INDEX [IFK_InvoiceLineInvoiceId] ON ""in..."
18,index,IFK_InvoiceLineTrackId,invoice_items,28,"CREATE INDEX [IFK_InvoiceLineTrackId] ON ""invo..."
19,index,IFK_PlaylistTrackTrackId,playlist_track,29,"CREATE INDEX [IFK_PlaylistTrackTrackId] ON ""pl..."
20,index,IFK_TrackAlbumId,tracks,30,"CREATE INDEX [IFK_TrackAlbumId] ON ""tracks"" ([..."
21,index,IFK_TrackGenreId,tracks,31,"CREATE INDEX [IFK_TrackGenreId] ON ""tracks"" ([..."
22,index,IFK_TrackMediaTypeId,tracks,32,"CREATE INDEX [IFK_TrackMediaTypeId] ON ""tracks..."
23,table,sqlite_stat1,sqlite_stat1,864,"CREATE TABLE sqlite_stat1(tbl,idx,stat)"
24,table,ranks,ranks,865,CREATE TABLE ranks (\n rank TEXT NOT NULL\n)
25,view,ManagementRoles,ManagementRoles,0,CREATE VIEW ManagementRoles AS\nSELECT m.first...

# What do we have here?

The sqlite_master table in a SQLite database has a listing of all the tables, functions, procedures, indices and fews stored
in the database.

Most databases have something similar, a table that keeps track of all the contents

*tables* are individual tables of data

an *index* is a hashed index or key value for a specific data tables.  An index speeds up the time it takes to access a 
specific row of a given table, but it takes up space in the database.   Typically there will be an index for the *key* or 
unique identifier for a give row.  We can create indices for other columns in the table (say a name or a phone number) 
that we know we will want to up frequently.

a *view* is a report or summary of the information contained in one or more tables.   A view is not stored like a table, but rather as the SQL commands needed to create the view.   This is really helpful for reports, summaries or questions that people often want to see.   The view acts like it is a table, but is stored as just commands, saving space and avoiding duplicating information.

# Now, let's look at the entire content of one particular table.

Pandas has a built in function to run an SQL query and store the output in a data frame

We have to supply the SQL query and the connector

The query "SELECT * FROM albums"

this means please get all (*) data from the Table named albums

In [11]:
albums_df=pd.read_sql_query("SELECT * FROM albums",con)

In [12]:
albums_df.head()

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2
2        3                      Restless and Wild         2
3        4                      Let There Be Rock         1
4        5                               Big Ones         3

## Pandas exercises based on the albums_df

In [ ]:
a.) What is the shape of the dataframe

In [ ]:
b.) Find out if any of the rows in album_df are missing data

Figure out two different ways to do this,  you will need to use Google or an LLM

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 347 entries, 0 to 346
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   AlbumId   347 non-null    int64
 1   Title     347 non-null    object
 2   ArtistId  347 non-null    int64
dtypes: int64(2), object(1)
memory usage: 8.3+ KB

In [ ]:
c.) How many distinct artists are there in this data frame?

In [ ]:
d.) Create a table or summary listing the number of albums per each artist id

In [ ]:
e.) Create a histogram that shows the number of albums per artist id